# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('beginDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.BooleanField()),
                ('theme', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('type', models.CharField(max_length=200)),
                ('idEdicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='satiUTFPR.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=63)),
                ('food', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=63)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('dateBirth', models.DateField()),
                ('cpf', models.CharField(max_length=15)),
                ('academicRegistry', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
