# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satiUTFPR', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lunch',
        ),
    ]
