# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default=None, upload_to=b'')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('theme', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['begin_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('fee', models.FloatField(default=0.0)),
                ('workload', models.IntegerField(default=0.0)),
                ('description', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='sati.Category')),
                ('edition', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='sati.Edition')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['begin_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('datePayment', models.DateField()),
                ('allowance', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('academic_registry', models.CharField(max_length=15, null=True)),
                ('role', models.IntegerField(choices=[(1, b'Admin'), (2, b'Instructor'), (3, b'Student')], default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTime', models.DateTimeField()),
                ('exitTime', models.DateTimeField()),
                ('idParticipant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Participant')),
                ('occurrence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=255)),
                ('raffleDate', models.DateTimeField()),
                ('idParticipant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Participant')),
                ('occurrence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('occupancy', models.IntegerField()),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spots', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='sati.Event')),
                ('instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='sati.Person')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Person'),
        ),
        migrations.AddField(
            model_name='participant',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Session'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrences', to='sati.Room'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrences', to='sati.Session'),
        ),
    ]
