# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='academic_registry',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
