# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='status2',
            field=models.BooleanField(default=True),
        ),
    ]
