# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-26 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ocurrence',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
