# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0002_auto_20160918_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
    ]
