# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0003_auto_20160911_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['begin_date']},
        ),
    ]
