# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='sati.Category'),
        ),
    ]
