# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0004_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AlterField(
            model_name='event',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='event',
            name='workload',
            field=models.IntegerField(default=0.0),
        ),
    ]
