# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0004_auto_20160911_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='charge',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='event',
            name='idEdicao',
        ),
        migrations.AddField(
            model_name='event',
            name='id_edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='editions', to='sati.Edition'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
