# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0004_auto_20160918_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='academic_registry',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
