# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0005_auto_20160911_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id_edition',
        ),
        migrations.AddField(
            model_name='event',
            name='edition',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='sati.Edition'),
        ),
    ]
