# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-15 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0005_auto_20160915_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='spots',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
