# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0006_session_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
