# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0007_participant_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
