# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0007_auto_20160911_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
