# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0010_auto_20160911_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
    ]
