# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0011_remove_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=b'123', max_length=32),
        ),
    ]
