# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0013_auto_20160912_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role2',
            field=models.IntegerField(choices=[(1, b'Admin'), (2, b'Instructor'), (3, b'Student')], default=3),
        ),
    ]
