# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0015_remove_person_role2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='session',
            name='idEvent',
        ),
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='sati.Event'),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sessions', to='sati.Person'),
        ),
    ]
