# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0016_auto_20160912_0324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['begin_date_time'],
            },
        ),
        migrations.RemoveField(
            model_name='ocurrence',
            name='idRoom',
        ),
        migrations.RemoveField(
            model_name='ocurrence',
            name='idSession',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='academicRegistry',
            new_name='academic_registry',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='space',
            new_name='occupancy',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='idOcurrence',
        ),
        migrations.RemoveField(
            model_name='raffle',
            name='idOcurrence',
        ),
        migrations.AlterField(
            model_name='presence',
            name='idParticipant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Participant'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='idParticipant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Participant'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Ocurrence',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurences', to='sati.Room'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurences', to='sati.Session'),
        ),
        migrations.AddField(
            model_name='presence',
            name='occurrence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Occurrence'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='occurrence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='sati.Occurrence'),
        ),
    ]
