# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sati', '0017_auto_20160912_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrences', to='sati.Room'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='occurrences', to='sati.Session'),
        ),
    ]
